name: Build and push off-chain docker image

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  docker:
    env:
      IMAGE_REPO: dappforce
      IMAGE_NAME: subsocial-offchain

    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Retrieve backend version
        id: version
        run: |
          echo "::set-output name=TAG_NAME::\
          $(grep '^  "version"' ./package.json | egrep -o '([0-9\.]+(-(alpha|beta)[0-9\.]+)?)')"
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:v${{ steps.version.outputs.TAG_NAME }}
